# Generated by Django 5.1.7 on 2025-05-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grade',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
