# Generated by Django 5.1.7 on 2025-05-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_teacherprofile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
