# Generated by Django 5.1.7 on 2025-05-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_grades'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grades',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grades',
            field=models.ManyToManyField(blank=True, null=True, related_name='grades', to='classes.grades'),
        ),
    ]
