# Generated by Django 5.1.7 on 2025-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_login_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
