# Generated by Django 5.1.7 on 2025-05-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_grades_studentprofile_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grades',
        ),
    ]
