# Generated by Django 5.1.7 on 2025-05-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject',
        ),
    ]
