# Generated by Django 5.1.7 on 2025-05-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_studentprofile_grades'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.studentprofile'),
        ),
    ]
