<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-05-21 19:00
=======
# Generated by Django 5.1.7 on 2025-05-21 17:43
>>>>>>> 0b1688a291ba3eaa15ee671bc5d446a56735be5a

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_studentprofile_grades'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='student',
<<<<<<< HEAD
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_grade', to='accounts.studentprofile'),
=======
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.studentprofile'),
>>>>>>> 0b1688a291ba3eaa15ee671bc5d446a56735be5a
        ),
    ]
