# Generated by Django 5.1.7 on 2025-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_studentprofile_grades'),
        ('classes', '0003_class_teacher_alter_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_classes', to='accounts.studentprofile'),
        ),
    ]
