# Generated by Django 5.1.7 on 2025-05-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='school_class',
        ),
        migrations.AddField(
            model_name='grades',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.class'),
            preserve_default=False,
        ),
    ]
